version: '3.9'

services:
  queuing-system:
    extends:
      file: common.yml
      service: common
    container_name: queuing-system
    image: turnly/queuing-system:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/queuing-system
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        PORT: ${HTTP_PORT}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/queuing-system:/app
    depends_on:
      - gateway
      - mongo
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.http.routers.queuing-system-rpc.entrypoints=web,websecure
      - traefik.http.routers.queuing-system-rpc.rule=PathPrefix(`/turnly.queuing_system.v1`)
      - traefik.http.routers.queuing-system-rpc.service=queuing-system-rpc
      - traefik.http.services.queuing-system-rpc.loadbalancer.server.scheme=h2c
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: queuing-system
      ENCRYPTION_SECRET:
      RABBITMQ_QUEUE: ${QUEUING_SYSTEM_RABBITMQ_QUEUE:-turnly.ms.queuing_system.queue}
      MONGO_DB: ${QUEUING_SYSTEM_MONGO_DB:-queuing_system_db}
