version: '3.9'

services:
  kibana:
    extends:
      file: common.yml
      service: common
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - kibana.turnly.local
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_URI}
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.kibana-public.entrypoints=kibana
      - traefik.http.routers.kibana-public.service=kibana-public
      - traefik.http.routers.kibana-public.rule=Host(`${APP_INFRA_DOMAIN}`)
      - traefik.http.services.kibana-public.loadbalancer.server.port=5601

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.kibana-public.middlewares=oauth-infra-middleware
