query GetServiceFields($serviceId: ID!) {
  getServiceFields(serviceId: $serviceId) {
    id
    label
    description
    type
    isRequired
    hasProcessors
    extra {
      key
      value
    }
  }
}
