query GetTicket($getTicketId: ID!) {
  getTicket(id: $getTicketId) {
    id
    status
    displayCode
    service {
      name
      description
    }
    location {
      name
      address
      longitude
      latitude
    }
    beforeYours
    calledToDesk
    customerId
  }
}
