export enum FieldTypes {
  NATIONAL_IDENTITY_CARD = 'national_identity_card',
  PASSPORT = 'passport',
  DRIVERS_LICENSE = 'drivers_license',
  SOCIAL_SECURITY_CARD = 'social_security_card',
  TEXT = 'text',
  LINK = 'link',
  EMAIL = 'email',
  PHONE = 'phone',
  DROP_DOWN = 'drop_down',
  LIST = 'list',
  NUMERIC = 'numeric',
  DATE = 'date',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  TEXTAREA = 'textarea',
  CURRENCY = 'currency',
  PERCENTAGE = 'percentage',
  PASSWORD = 'password',
}
